name: Build

on: [push]

jobs:
  build-publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@ianhomer'
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_PAT }}
    - name: service test
      run: |
        npm run test
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Test deployment
      run: |
        npm run cypress:run
      env:
        CYPRESS_baseUrl: https://example.things.purplepip.com/
