on:
  schedule:
  - cron: 0 0 * * *
name: Update
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/
        scope: '@ianhomer'
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: ian@purplepip.com
        AUTHOR_NAME: Ian
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
        UPDATE_COMMAND: npm
        NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_PAT }}
      with:
        args: update
